<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [18 24 30 36 42]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [16]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples


# you can free to change all these codes/structure
# here A and B are list of lists
#def matrix_mul(A, B):
    # write your code
#   return(#multiplication_of_A_and_B)
    
#matrix_mul(A, B)


# Define list A
A = [[2,1],
    [2,3],
    [4,3]]

# Define list B
B = [[5,4],
    [6,3]]

res = [[0,0],
      [0,0]]


for i in range(2):
    for j in range(2):
        for k in range(2):
            res[i][j] += A[i][k] * B[k][j]
print('Print list A :')
for r in A:
    print(r)


print('Print list B :')
for r in B:
    print(r)

print('Multifiaction of two matrix: ')
for r in res:
    print(r)

Print list A :
[2, 1]
[2, 3]
[4, 3]
Print list B :
[5, 4]
[6, 3]
Multifiaction of two matrix: 
[16, 11]
[28, 17]


<h3> Q2: Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [18]:
#from random import uniform
from random import uniform
import pandas as pd
A = [0, 5, 27, 6, 13, 28, 100, 45, 10, 79]
#w = [0.0, 0.15, 0.086,0.09600, 0.09000,0.08900, 0.019, 0.041, 0.31, 0.25]
l = len(A)

def pickNum(A, l):
    sum=0
    for i in range(l):
        sum +=A[i]
    a_dash = []
    for i in range(l):
        b=A[i]/sum
        a_dash.append(b)
        
        #series = pd.series(a_dash)
        #cum = series.cumsum(skipna=Flase)
        Series = pd.Series(a_dash)
        cum = Series.cumsum(skipna = False)
        
    
    svalue = uniform(0.0, 1.0)
    r = svalue
    print(r)
    
    
    if r<cum[1]:
        return 1
    elif r<cum[1] and r <cum[2]:
        return 2
    elif r<cum[3]:
        return 3
    elif r<cum[4]:
        return 4
    elif r<cum[5]:
        return 5
    elif r<cum[6]:
        return 6
    elif r<cum[7]:
        return 7
    elif r<cum[8]:
        return 8
    elif r<cum[9]:
        return 9

def sampleM():
    num = pickNum(A, l)
    print(A[num])
sampleM()

0.0008300955723803405
5


<h3> Q3: Replace the digits in the string with #</h3>

Consider a string that will have digits in that, we need to remove all the characters which are not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [19]:
import re
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# you can free to change all these codes/structure
# String: it will be the input to your program

digit = input('Enter the digits: ')

def ReplaceDigits(digit):
    digit2 =  ''
    for i in digit:
         if i.isnumeric():
                digit2 = digit2 + '#'             
            
    """
    Modified string which is after replacing with # digits
    """
    #print(digit.replace(digit, '#'))
    print(digit2)
    
    print('Print the digits which is replaced with ### values')
    
    return digit
ReplaceDigits(digit)

Enter the digits: #2we345
####
Print the digits which is replaced with ### values


'#2we345'

<h3> Q4: Students marks dashboard</h3>

Consider the marks list of class students given in two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on. <br><br>

Your task is to print the name of students

<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks.</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]

a. 
student8  98
student10 80
student2  78
student5  48
student7  47

b.
student3 12
student4 14
student9 35
student6 43
student1 45

c.
student9 35
student6 43
student1 45
student7 47
student5 48
</pre>

In [20]:
Student=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]

#
Stud = {'student1':45,'student2':78,'student3':12,'student4':14, 'student5':48,'student6':43,'student7':47,
      'student8':98,'student9':35,'student10':80}
print('Students Marks dash board')
Stud

Students Marks dash board


{'student1': 45,
 'student10': 80,
 'student2': 78,
 'student3': 12,
 'student4': 14,
 'student5': 48,
 'student6': 43,
 'student7': 47,
 'student8': 98,
 'student9': 35}

In [21]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

import collections
# a) Who got top 5 ranks, in the descending order of marks 

k = collections.Counter(Stud)
t5 = k.most_common(5)

print('Top 5 ranks, in the descending order of marks')
for i in t5: 
    print(i[0]," :",i[1]," ")

print('-------------------------------------------------------------------------')

# b) Who got least 5 ranks, in the increasing order of marks

print('Top 5 ranks, in the increasing order of marks')
sd = sorted(Stud.items(), key =lambda x:x[1])
for i in range(5):
    print(sd[i])

print('-------------------------------------------------------------------------')
# C) Who got marks between >25th percentile <75th percentile, in the increasing order of marks     

print('Marks between >25th percentile <75th percentile, in the increasing order of marks')

Stud1 = {45:'student1', 78:'student2',12:'student3',14:'student4', 48:'student5',43:'student6',47:'student7',
      98:'student8',35:'student9',80:'student10'}

sort = sorted(Stud1)
#print(sort)

for i in range(len(sort)):
    if sort[i] > 25 and sort[i] < 75:
        print(Stud1.get(sort[i]),sort[i])    

print('-------------------------------------------------------------------------')
#top_5_students, least_5_students, students_within_25_and_75 = display_dash_board(students, marks)

print('Student Marks ')

stud_board = dict(zip(Student, Marks))
print(stud_board)

Top 5 ranks, in the descending order of marks
student8  : 98  
student10  : 80  
student2  : 78  
student5  : 48  
student7  : 47  
-------------------------------------------------------------------------
Top 5 ranks, in the increasing order of marks
('student3', 12)
('student4', 14)
('student9', 35)
('student6', 43)
('student1', 45)
-------------------------------------------------------------------------
Marks between >25th percentile <75th percentile, in the increasing order of marks
student9 35
student6 43
student1 45
student7 47
student5 48
-------------------------------------------------------------------------
Student Marks 
{'student1': 45, 'student2': 78, 'student3': 12, 'student4': 14, 'student5': 48, 'student6': 43, 'student7': 47, 'student8': 98, 'student9': 35, 'student10': 80}


<h3> Q5: Find the closest points</h3>

Consider you are given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> your task is to find 5 closest points(based on cosine distance) in S from P

<br>Cosine distance between two points (x,y) and (p,q) is defined as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1)(6,0),(1,-1)]
P= (3,-4)
<img src='https://i.imgur.com/vIFPOcG.jpg', width=300>
Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>

In [22]:
import math

# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# you can free to change all these codes/structure


# here S is list of tuples and P is a tuple ot len=2
def closest_points_to_p():
    S.sort(key=lambda x: math.sqrt((float(x[0]) -3) ** 2 +
                                  (float(x[1]) -(-4)) ** 2))
    # write your code here
#    return closest_points_to_p  # its list of tuples
S = [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P = (3,-4)
    
#points = closest_points_to_p(S[:5], (3,-4))
print('Print the closest five points:')
print(S[:5]) #print the returned values

Print the closest five points:
[(1, 2), (3, 4), (-1, 1), (6, -7), (0, 6)]


 Question -5:- Using lambda funtion I got the nearest 5 point given the list of tuples

<h3> Q6: Find which line separates oranges and apples</h3>

Consider you are given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string format, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: You need to do string parsing here and get the coefficients of x,y and intercept.
</pre>
Your task here is to print "YES"/"NO" for each line given. You should print YES, if all the red points are one side of the line and blue points are on other side of the line, otherwise you should print NO.
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/DoQf7mE.jpg' width=400>
Output:
YES
NO
NO
YES
</pre>

In [23]:
#import math
#import re
#import matplotlib.pyplot as plt 
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings
# you can free to change all these codes/structure
#------------

#print(lines[0].replace(R[2]))
#print(R[1])
#for i in lines:

#print(int(lst1[1][1]))
#for i in range(len(lst1)):
#             for j in range(len(R)):
#                            if (int(lst1[i][0])*int(R[j][0]) + int(lst1[i][1])*int(R[j][1]) + float(lst1[j][2])) > 0:
#                                C = 0
#                            else:
#                                 C = 1
##                                 break
#                            if C == 0:
##                                 print('Yes')
#                            else:
#                                 print('No')              

In [24]:
import math
import re
R= [(1,1),(2,1),(4,2),(2,4)]
B = [(-2,-1),(-1,-2),(-3,-2),(-3,-1)]
lines = ["1x+1y+0", "1x-1y+0", "1x+0y-3", "0x+1y-0.5"]
lst1 = []
for i in lines:
    z = re.findall(r'[\d\.\-\+]+', i)
    lst1.append(z)
for i in range(len(lst1)):
              for j in range(len(R)):
                            if (int(lst1[i][0])*int(R[j][0]) + int(lst1[i][1])*int(R[j][1]) + float(lst1[i][2])) > 0:
                                C = 0
                            else:
                                C = 1
                                #print('yeah',i)
                                break
              if C == 0:
                print('Yes')
              else:
                print('No')

Yes
No
No
Yes


<h3> Q7: Filling the missing values in the specified format</h3>

You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 

<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4
</pre>



In [25]:
import re
def curve_smoothing(string):
    blank_count=0
    value_count = 0
    splitString = string.split(",")
    print("Input:", string)
    totalNumbers = len(splitString)
    for i in splitString:
        if i=="_":
            blank_count+=1
        else:
            value_count=int(i) + int(value_count)
    sequenceNumber = int(value_count/totalNumbers)
    if(blank_count!=0):
        Output = string.replace("_",str(sequenceNumber),blank_count)
        
    print('Outpu:', Output)
    S1="_,_,_,24"
    print()
    S2="40,_,_,_,60"
    print()
    S3="80,_,_,_,_"
    print()
    S4="_,_,30,_,_,_,50,_,_"
    
curve_smoothing('_,_,_,24')
curve_smoothing("40,_,_,_,60")
curve_smoothing("80,_,_,_,_")
curve_smoothing("_,_,30,_,_,_,50,_,_")

Input: _,_,_,24
Outpu: 6,6,6,24



Input: 40,_,_,_,60
Outpu: 40,20,20,20,60



Input: 80,_,_,_,_
Outpu: 80,16,16,16,16



Input: _,_,30,_,_,_,50,_,_
Outpu: 8,8,30,8,8,8,50,8,8





<h3> Q8: Find the probabilities</h3>

You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. The first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. The second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>



In [26]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings

# you can free to change all these codes/structure
#def compute_conditional_probabilites(A):
    # your code
    # print the output as per the instructions
#
#    A = [[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]
#compute_conditional_probabilites(A)

In [27]:
A = [['F1', 'S1'],
     ['F2', 'S2'], 
     ['F3', 'S3'], 
     ['F1', 'S2'], 
     ['F2', 'S3'], 
     ['F3', 'S2'], 
     ['F2', 'S1'], 
     ['F4', 'S1'], 
     ['F4', 'S3'], 
     ['F5', 'S1']]

dictionary1 = {'F1S1': 0,'F2S1': 0,'F3S1': 0,'F4S1': 0,'F5S1': 0,'F1S2': 0,'F2S2': 0,'F3S2': 0,'F4S2': 0,'F5S2': 0,'F1S3': 0,
'F2S3': 0,
'F3S3': 0,
'F4S3': 0,
'F5S3': 0,
}

dictionary2 = {
'S1': 0,
'S2': 0,
'S3': 0
}


def compute_conditional_probabilites(A):
    for i in range(len(A)):
       k = A[i][0] + A[i][1]
       dictionary1[k] += 1
       dictionary2[A[i][1]] += 1

compute_conditional_probabilites(A)


#a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
print('a__________________________________________________________________________________________________')
print('Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)', (dictionary1['F1S1']/dictionary2['S1'],
                                                                      dictionary1['F1S2']/dictionary2['S2'],
                                                                      dictionary1['F1S3']/dictionary2['S3']))
                                    
#b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
print('b__________________________________________________________________________________________________')
print('probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)', (dictionary1['F2S1']/dictionary2['S1'],
                                                                        dictionary1['F2S2']/dictionary2['S2'],
                                                                        dictionary1['F3S1']/dictionary2['S3']))

#print('probability of  P(F=F2|S==S1)', (dictionary1['F2S1']/dictionary2['S1']))
#print('probability of  P(F=F2|S==S2)', (dictionary1['F2S2']/dictionary2['S2']))
#print('probability of  P(F=F2|S==S3)', (dictionary1['F3S1']/dictionary2['S3']))
#----------------
#c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
print('c__________________________________________________________________________________________________')
print('probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)', (dictionary1['F3S1']/dictionary2['S1'],
                                                                     dictionary1['F3S2']/dictionary2['S2'],
                                                                     dictionary1['F3S3']/dictionary2['S3']))

#d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
print('d__________________________________________________________________________________________________')
print('probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)', (dictionary1['F4S1']/dictionary2['S1'],
                                                                     dictionary1['F4S2']/dictionary2['S2'],
                                                                     dictionary1['F4S3']/dictionary2['S3']))

#e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
print('e__________________________________________________________________________________________________')
print('probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)', (dictionary1['F5S1']/dictionary2['S1'],
                                                                     dictionary1['F5S2']/dictionary2['S2'],
                                                                     dictionary1['F5S3']/dictionary2['S3']))

a__________________________________________________________________________________________________
Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3) (0.25, 0.3333333333333333, 0.0)
b__________________________________________________________________________________________________
probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3) (0.25, 0.3333333333333333, 0.0)
c__________________________________________________________________________________________________
probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3) (0.0, 0.3333333333333333, 0.3333333333333333)
d__________________________________________________________________________________________________
probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3) (0.25, 0.0, 0.3333333333333333)
e__________________________________________________________________________________________________
probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3) (0.25, 0.0, 0.0)


<h3> Q9: Operations on sentences </h3>

You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 unique values"
S2= "the second column S will contain only 3 unique values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [28]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings

# you can free to change all these codes/structure
#def string_features(S1, S2):
#    # your code
#    return a, b, c

#S1= "the first column F will contain only 5 uniques values"
#S2= "the second column S will contain only 3 uniques values"
#a,b,c = string_features(S1, S2)
#print(#the above values)

In [29]:
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"

k = 0
x = []
y = []
z = []
count = 0            # count var for count the word is in string

for i in S1.split():
    x.append(i)
    
for j in S2.split():
    if j ==x[k]:
        count = count +1
    else:

        y.append(j)
        z.append(x[k])
    k = k + 1

print('1.Number of common words between S1 and S2. . . . . . :\n' ,count)
print()
print('2.Words in S1 but not in S2. . . . . . :\n', z)
print()
print('3.Words in S2 but not in S1. . . . . . :\n', y)       
    

1.Number of common words between S1 and S2. . . . . . :
 7

2.Words in S1 but not in S2. . . . . . :
 ['first', 'F', '5']

3.Words in S2 but not in S1. . . . . . :
 ['second', 'S', '3']


<h3> Q10: Error Function</h3>

You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.44982
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [30]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings
import math

# you can free to change all these codes/structure
#def compute_log_loss(A):
    # your code
    
#    return loss

#A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
#loss = compute_log_loss(A)
#print(# the above loss)

In [31]:
import math
A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]

print(len(A))
print(A[0][1])
loss=0
for i in range(len(A)):
    #print("h")
    loss=loss+(-(1/8)*((A[i][0]*math.log10(A[i][1])+((1-A[i][0])*math.log10(1-A[i][1])))))
print (loss) 
print(1/8)

8
0.4
0.42430993457031635
0.125
