# Numpy in Python - Applied ML

In [116]:
import numpy as np

In [117]:
a = ([1,3,5,3,4,6,])
a

[1, 3, 5, 3, 4, 6]

In [118]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [119]:
l = range(10)
%timeit [i **2 for i in l] # % timeit tell us how much time took for this process

12.1 µs ± 967 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [120]:
a= np.arange(10)
%timeit a **2
a

2 µs ± 270 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [121]:
# 1 D array

a = np.array([2,4,5,1])
a

array([2, 4, 5, 1])

In [122]:
# 2 -D array

b =np.array([[0,3,4], [3,2,4]])
b

array([[0, 3, 4],
       [3, 2, 4]])

In [123]:
b.ndim

2

In [124]:
b.shape # two rows and three columns

(2, 3)

In [125]:
len(b)

2

In [126]:
# 3-D array

c = np.array([[[3,2,5], [9,7,4]], [[2,1,0],[9,4,3]]])
c

array([[[3, 2, 5],
        [9, 7, 4]],

       [[2, 1, 0],
        [9, 4, 3]]])

In [127]:
c.ndim

3

In [128]:
c.shape

(2, 2, 3)

In [129]:
len(c)

2

In [130]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [131]:
d = np.arange(1, 10, 3) # start 1, end 10 and step size 3
d

array([1, 4, 7])

In [132]:
e = np.linspace(0, 1, 6) # linear space is give the start 0, end 1 and point 6
e

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [133]:
f =np.eye(4) # identity metrix, diagnoal metrix, all the diagnoal metrix is zero
f

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [134]:
g = np.eye(3,2)
g

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [135]:
# create the array using diagnoal function

h = np.diag([1,2,3,4])
h

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [136]:
# create random array using random

i = np.random.rand(4)
i


array([0.05778255, 0.05818612, 0.64148065, 0.12374444])

In [137]:
j = np.array(2)

j.dtype

dtype('int32')

In [138]:
k = np.array([2+1j,2+4j])

print(k.dtype)

complex128


In [139]:
l = np.array([True, False, True, False])
print(l.dtype)


bool


In [140]:
m = np.array(['Ram', 'Viviek', 'Sachin'])

m.dtype

dtype('<U6')

In [59]:
#
n = np.diag([1, 2, 3])


print(n[2, 2])


3


In [60]:
p =np.diag([1,2,3,4,5])
p

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [61]:
np.diag(p)

array([1, 2, 3, 4, 5])

In [62]:
#
o = np.array(20.2)
o.dtype

dtype('float64')

In [63]:
q = np.zeros([3,3])
q

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [64]:
q[2, 1]=5
q

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 5., 0.]])

# Slicing

In [65]:
r = np.arange(10)
r

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
r[3:8:2] # strt index:end index: step
r

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
r[5:]=10
r

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [68]:
b = np.arange(5)
r[5:] = b[::-1]   # -1 is revers order
r

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

# copies and views

In [69]:
w = np.array([10])
w

array([10])

In [70]:
b = a[: : 2].copy()
b

array([1, 3])

In [71]:
a = np.random.randint(0,20,15)
a

array([ 8,  4,  6, 16, 11,  6, 10,  4, 18, 15,  5,  8,  8, 18, 11])

In [72]:
# indexing wiht an array of inte

a =np.arange(0,110,10)
a

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [73]:
a[[2,3,5,3,2]]

array([20, 30, 50, 30, 20])

In [74]:
a[[2,5]]= -20 # assing the new values of list
a

array([  0,  10, -20,  30,  40, -20,  60,  70,  80,  90, 100])

# Numrical operation on Numpy 

In [75]:
# basic operation
import numpy as np

a = np.array([1,2,3,4,])

a + 1


array([2, 3, 4, 5])

In [76]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [77]:
#b = np.ones(4)  
#b
b = np.ones(4) + 1

a - b

array([-1.,  0.,  1.,  2.])

In [78]:
a * b

array([2., 4., 6., 8.])

In [79]:
# diagnoal matrix 
# matrix multification

c = np.diag([1, 2, 3, 4])

print(c*c)
print('------------')
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
------------
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [80]:
# comparision elements wiae comparisons
a = np.array([1, 2, 3, 4])
b = np.array([5, 2, 2, 4])

a==b

array([False,  True, False,  True])

In [81]:
# comparision
a > b

array([False, False,  True, False])

In [82]:
# array comparisons
a = np.array([1, 2, 3, 4])
b = np.array([5, 2, 2, 4])
c = np.array([5, 3, 2, 4])

np.array_equal(a ,b)


False

# Logical operation

In [83]:
a = np.array([1, 1, 0, 0], dtype=bool)
a = np.array([1, 0, 1, 0], dtype=bool)

np.logical_or(a, b)

array([ True,  True,  True,  True])

In [84]:
np.logical_and(a, b)

array([ True, False,  True, False])

In [85]:
a = np.arange(5)

np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [86]:
np.log(a)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [87]:
np.byte(a)

array([0, 1, 2, 3, 4], dtype=int8)

In [88]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [89]:
np.exp2(a)

array([ 1.,  2.,  4.,  8., 16.])

# Shape mismatch

In [90]:
a = np.array(4)

a + np.array(1,2)

TypeError: data type not understood

In [91]:
# basic reductions

a = np.array([1,2,3,4])

np.sum(a)

10

In [92]:
a.sum(axis=0)

10

In [93]:
a.argmin()

0

In [94]:
a.argmax()

3

In [95]:
# logical operation



In [96]:
np.all([True, True, False]) # this all is and


False

In [97]:
np.any([True, False, False]) # this any is or

True

In [98]:
a = np.array([1,2,3,2])
b = np.array([2,2,3,2])
c = np.array([6,4,4,5])

((a<=b) & (b<=c)).all()  # its check elements wise

True

# static operations

In [99]:
x = np.array([1,2,3])
y = np.array([[1,2,3], [5,6,1]])

x.mean()

2.0

In [100]:
np.median(x)

2.0

In [101]:
np.median(y, axis=-1)

array([2., 5.])

In [102]:
x.std()# standred devision

0.816496580927726

# boradcosting


In [103]:
a =np.array([[0,0,0],[10,10,10],[20,20,20],[30,30,30]])
a

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [104]:
b = np.array([0,1,2])
b


array([0, 1, 2])

In [105]:
c = a + b
c

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [115]:
a = np.tile(np.arange(0,40,10), (3, 1))
print(a)

print('------------------------')
a =a.T
print(a)

[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]
------------------------
[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]


In [121]:
# Ravel flatened array convert 2d array to one d array

a = np.array([[1,2,3],[4,5,6], [2,4,3]])
a.ravel()


array([1, 2, 3, 4, 5, 6, 2, 4, 3])

In [122]:
print(a.shape)
print(a)

(3, 3)
[[1 2 3]
 [4 5 6]
 [2 4 3]]


# Resizing  and sorting data

In [124]:
a = np.arange(4)
a.resize((8,))
a

array([0, 1, 2, 3, 0, 0, 0, 0])

In [125]:
a = np.array([[5,4,3],[2,3,2]])
b =np.sort(a, axis=1)
b

array([[3, 4, 5],
       [2, 2, 3]])

In [127]:
a.sort(axis=1)
a

array([[3, 4, 5],
       [2, 2, 3]])

In [136]:
# arg sort is show the indexing sort it 

a = np.array([4,2,1,3])

j= np.argsort(a)
j


array([2, 1, 3, 0], dtype=int64)

In [137]:
a[j]

array([1, 2, 3, 4])